asm.exe: ..\src\comfun.h ..\src\comfun.cpp ..\src\interpreter.h ..\src\interpreter.cpp ..\src\asm_windows.cpp
	g++ ..\src\comfun.cpp ..\src\interpreter.cpp ..\src\asm_windows.cpp -o asm.exe

clean:
	del *.exe
